server:
  port: 10086
  servlet:
    context-path: /api


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/for_test?serverTimezone=Asia/Shanghai
    username: viki
    password: abcd.123456
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'


logging:
  level:
    sql: debug
    org:
      springframework:
        data: trace
      hibernate:
        type: trace
        event: trace
