server:
  port: 10086
  servlet:
    context-path: /api


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/antd-access?serverTimezone=Asia/Shanghai
    username: viki
    password: abcd.123456
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      show-sql: true