server:
  port: 10086
  servlet:
    context-path: /api


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/antd-access?serverTimezone=Asia/Shanghai
    username: viki
    password: abcd.123456
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: 'update'


logging:
  level:
    sql: info
    org:
      springframework:
        data: info
      hibernate:
        type: info
        event: info
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr([%5.15t]){faint} %clr(%-15.15logger{39}){cyan} %clr(:){faint} %m%n'
